### PR TITLE
Extremely accurate sin/cos

### PR DESCRIPTION
**Pull request by gwoltman**
More accurate trig functions via -use ULTRA_TRIG.
Improves max 5M exponent by about 60,000.  Updated FFTconfig routines to follow.

### CODE REVIEW

**Comment by gwoltman** [comment]
Hi,

This is what I see for exponent 91000001 (small enough so that none of the
MM_CHAINs get set).  A clear win for ultra_trig.

Ernst sine, sun cosine, rocm3.1:

2020-04-22 03:51:52 config: -prp 91000001 -use STATS
2020-04-22 03:51:52 device 0, unique id ''
2020-04-22 03:51:52 gfx906+sram-ecc-0 91000001 FFT: 5M 1K:10:256 (17.36 bpw)
2020-04-22 03:51:52 gfx906+sram-ecc-0 Expected maximum carry32: 2AC20000
2020-04-22 03:51:53 gfx906+sram-ecc-0 OpenCL args "-DEXP=91000001u
-DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u
-DWEIGHT_STEP=0x1.8fcc46340429cp+0 -DIWEIGHT_STEP=0x1.47d879a46ac5ep-1
-DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0
-DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1 -DSTATS=1
 -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-04-22 03:51:58 gfx906+sram-ecc-0 OpenCL compilation in 5.44 s
2020-04-22 03:52:01 gfx906+sram-ecc-0 91000001 OK        0 loaded:
blockSize 1000, 0000000000000003
2020-04-22 03:52:04 gfx906+sram-ecc-0 Roundoff: N=3128, mean 0.046405, SD
0.035565, CV 0.766401, max 0.095988, z 12.8 (pErr 98.205054%)
2020-04-22 03:52:06 gfx906+sram-ecc-0 91000001 OK     2000   0.00%; 1586
us/it; ETA 1d 16:06; 02f1fa01c061997d (check 1.80s)
2020-04-22 03:52:50 gfx906+sram-ecc-0 Roundoff: N=29028, mean 0.073403, SD
0.004132, CV 0.056296, max 0.101783, z 103.2 (pErr 0.000000%)
2020-04-22 03:52:52 gfx906+sram-ecc-0 91000001 OK    30000   0.03%; 1587
us/it; ETA 1d 16:07; 701ddc5f3e04ad21 (check 1.78s)
2020-04-22 03:53:40 gfx906+sram-ecc-0 Roundoff: N=31030, mean 0.073389, SD
0.004119, CV 0.056128, max 0.102176, z 103.6 (pErr 0.000000%)
2020-04-22 03:53:41 gfx906+sram-ecc-0 91000001 OK    60000   0.07%; 1583
us/it; ETA 1d 15:59; 2f76279d4029e670 (check 1.75s)
2020-04-22 03:53:49 gfx906+sram-ecc-0 Stopping, please wait..
2020-04-22 03:53:51 gfx906+sram-ecc-0 Roundoff: N=7006, mean 0.073331, SD
0.004021, CV 0.054833, max 0.099947, z 106.1 (pErr 0.000000%)
2020-04-22 03:53:53 gfx906+sram-ecc-0 91000001 OK    66000   0.07%; 1592
us/it; ETA 1d 16:12; 29ac9412239d3ee6 (check 1.70s)
2020-04-22 03:53:53 gfx906+sram-ecc-0 Exiting because "stop requested"
2020-04-22 03:53:53 gfx906+sram-ecc-0 Bye

ultra, rocm 3.1:

2020-04-22 03:54:01 config: -device 0 -block 1000 -log 30000
2020-04-22 03:54:01 config: -prp 91000001 -use STATS,ULTRA_TRIG
2020-04-22 03:54:01 device 0, unique id ''
2020-04-22 03:54:01 gfx906+sram-ecc-0 91000001 FFT: 5M 1K:10:256 (17.36 bpw)
2020-04-22 03:54:01 gfx906+sram-ecc-0 Expected maximum carry32: 2AC20000
2020-04-22 03:54:02 gfx906+sram-ecc-0 OpenCL args "-DEXP=91000001u
-DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u
-DWEIGHT_STEP=0x1.8fcc46340429cp+0 -DIWEIGHT_STEP=0x1.47d879a46ac5ep-1
-DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0
-DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1 -DSTATS=1
-DULTRA_TRIG=1  -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-04-22 03:54:08 gfx906+sram-ecc-0 OpenCL compilation in 5.43 s
2020-04-22 03:54:10 gfx906+sram-ecc-0 91000001 OK        0 loaded:
blockSize 1000, 0000000000000003
2020-04-22 03:54:13 gfx906+sram-ecc-0 Roundoff: N=3128, mean 0.043606, SD
0.033414, CV 0.766286, max 0.092051, z 13.7 (pErr 71.641405%)
2020-04-22 03:54:15 gfx906+sram-ecc-0 91000001 OK     2000   0.00%; 1594
us/it; ETA 1d 16:18; 02f1fa01c061997d (check 1.77s)
2020-04-22 03:55:00 gfx906+sram-ecc-0 Roundoff: N=29028, mean 0.068962, SD
0.003866, CV 0.056058, max 0.095192, z 111.5 (pErr 0.000000%)
2020-04-22 03:55:01 gfx906+sram-ecc-0 91000001 OK    30000   0.03%; 1589
us/it; ETA 1d 16:09; 701ddc5f3e04ad21 (check 1.74s)
2020-04-22 03:55:49 gfx906+sram-ecc-0 Roundoff: N=31030, mean 0.068976, SD
0.003897, CV 0.056492, max 0.101746, z 110.6 (pErr 0.000000%)
2020-04-22 03:55:51 gfx906+sram-ecc-0 91000001 OK    60000   0.07%; 1592
us/it; ETA 1d 16:13; 2f76279d4029e670 (check 1.84s)
2020-04-22 03:55:57 gfx906+sram-ecc-0 Stopping, please wait..
2020-04-22 03:55:59 gfx906+sram-ecc-0 Roundoff: N=6005, mean 0.069066, SD
0.003908, CV 0.056587, max 0.089921, z 110.3 (pErr 0.000000%)
2020-04-22 03:56:01 gfx906+sram-ecc-0 91000001 OK    65000   0.07%; 1592
us/it; ETA 1d 16:12; af8e31086a1607b6 (check 1.56s)
2020-04-22 03:56:01 gfx906+sram-ecc-0 Exiting because "stop requested"
2020-04-22 03:56:01 gfx906+sram-ecc-0 Bye

I'll try your exponent next with all the MM_CHAINS disabled

Regards,
George

**Comment by gwoltman** [comment]
And here is your exponent.   Again ultra wins.   Is this a rocm 3.3 issue
or perhaps the MM_CHAIN settings were not the same for each of your runs?

2020-04-22 04:04:12 config: -device 0 -block 1000 -log 30000
2020-04-22 04:04:12 config: -prp 95157709 -use STATS
2020-04-22 04:04:12 device 0, unique id ''
2020-04-22 04:04:12 gfx906+sram-ecc-0 95157709 FFT: 5M 1K:10:256 (18.15 bpw)
2020-04-22 04:04:12 gfx906+sram-ecc-0 Expected maximum carry32: 4A160000
2020-04-22 04:04:13 gfx906+sram-ecc-0 OpenCL args "-DEXP=95157709u
-DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u
-DWEIGHT_STEP=0x1.cd797e5cd5b3ap+0 -DIWEIGHT_STEP=0x1.1c07552665bcdp-1
-DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0
-DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1 -DSTATS=1
 -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-04-22 04:04:19 gfx906+sram-ecc-0 OpenCL compilation in 5.74 s
2020-04-22 04:04:21 gfx906+sram-ecc-0 95157709 OK        0 loaded:
blockSize 1000, 0000000000000003
2020-04-22 04:04:24 gfx906+sram-ecc-0 Roundoff: N=3128, mean 0.139511, SD
0.106926, CV 0.766437, max 0.283466, z 3.4 (pErr 100.000000%)
2020-04-22 04:04:26 gfx906+sram-ecc-0 95157709 OK     2000   0.00%; 1438
us/it; ETA 1d 14:00; c402a10d2ef33b02 (check 1.88s)
2020-04-22 04:05:10 gfx906+sram-ecc-0 Roundoff: N=29028, mean 0.220921, SD
0.012595, CV 0.057011, max 0.313126, z 22.2 (pErr 0.002430%)
2020-04-22 04:05:12 gfx906+sram-ecc-0 95157709 OK    30000   0.03%; 1588
us/it; ETA 1d 17:57; 44581a911dd4c615 (check 1.75s)
2020-04-22 04:05:59 gfx906+sram-ecc-0 Roundoff: N=31030, mean 0.220925, SD
0.012547, CV 0.056795, max 0.318497, z 22.2 (pErr 0.002183%)
2020-04-22 04:06:01 gfx906+sram-ecc-0 95157709 OK    60000   0.06%; 1573
us/it; ETA 1d 17:33; f0c6a70ab8eb83b6 (check 1.75s)
2020-04-22 04:06:04 gfx906+sram-ecc-0 Stopping, please wait..
2020-04-22 04:06:06 gfx906+sram-ecc-0 Roundoff: N=4003, mean 0.221085, SD
0.012338, CV 0.055805, max 0.279707, z 22.6 (pErr 0.001367%)
2020-04-22 04:06:08 gfx906+sram-ecc-0 95157709 OK    63000   0.07%; 1567
us/it; ETA 1d 17:23; 62b3c215360ba5c8 (check 1.75s)
2020-04-22 04:06:08 gfx906+sram-ecc-0 Exiting because "stop requested"
2020-04-22 04:06:08 gfx906+sram-ecc-0 Bye

2020-04-22 04:06:22 config: -device 0 -block 1000 -log 30000
2020-04-22 04:06:22 config: -prp 95157709 -use STATS,ULTRA_TRIG
2020-04-22 04:06:22 device 0, unique id ''
2020-04-22 04:06:22 gfx906+sram-ecc-0 95157709 FFT: 5M 1K:10:256 (18.15 bpw)
2020-04-22 04:06:22 gfx906+sram-ecc-0 Expected maximum carry32: 4A160000
2020-04-22 04:06:23 gfx906+sram-ecc-0 OpenCL args "-DEXP=95157709u
-DWIDTH=1024u -DSMALL_HEIGHT=256u -DMIDDLE=10u
-DWEIGHT_STEP=0x1.cd797e5cd5b3ap+0 -DIWEIGHT_STEP=0x1.1c07552665bcdp-1
-DWEIGHT_BIGSTEP=0x1.ae89f995ad3adp+0
-DIWEIGHT_BIGSTEP=0x1.306fe0a31b715p-1 -DPM1=0 -DAMDGPU=1 -DSTATS=1
-DULTRA_TRIG=1  -cl-fast-relaxed-math -cl-std=CL2.0 "
2020-04-22 04:06:28 gfx906+sram-ecc-0 OpenCL compilation in 5.47 s
2020-04-22 04:06:31 gfx906+sram-ecc-0 95157709 OK        0 loaded:
blockSize 1000, 0000000000000003
2020-04-22 04:06:34 gfx906+sram-ecc-0 Roundoff: N=3128, mean 0.131589, SD
0.100861, CV 0.766484, max 0.271196, z 3.7 (pErr 100.000000%)
2020-04-22 04:06:36 gfx906+sram-ecc-0 95157709 OK     2000   0.00%; 1598
us/it; ETA 1d 18:15; c402a10d2ef33b02 (check 1.75s)
2020-04-22 04:07:21 gfx906+sram-ecc-0 Roundoff: N=29028, mean 0.208244, SD
0.011890, CV 0.057096, max 0.287052, z 24.5 (pErr 0.000115%)
2020-04-22 04:07:22 gfx906+sram-ecc-0 95157709 OK    30000   0.03%; 1594
us/it; ETA 1d 18:08; 44581a911dd4c615 (check 1.76s)
2020-04-22 04:08:10 gfx906+sram-ecc-0 Roundoff: N=31030, mean 0.208312, SD
0.011971, CV 0.057468, max 0.301898, z 24.4 (pErr 0.000143%)
2020-04-22 04:08:12 gfx906+sram-ecc-0 95157709 OK    60000   0.06%; 1589
us/it; ETA 1d 17:59; f0c6a70ab8eb83b6 (check 1.78s)
2020-04-22 04:08:16 gfx906+sram-ecc-0 Stopping, please wait..
2020-04-22 04:08:18 gfx906+sram-ecc-0 Roundoff: N=5004, mean 0.208304, SD
0.011991, CV 0.057563, max 0.291509, z 24.3 (pErr 0.000150%)
2020-04-22 04:08:20 gfx906+sram-ecc-0 95157709 OK    64000   0.07%; 1573
us/it; ETA 1d 17:33; 68402a352268c64e (check 1.75s)
2020-04-22 04:08:20 gfx906+sram-ecc-0 Exiting because "stop requested"
2020-04-22 04:08:20 gfx906+sram-ecc-0 Bye

**Comment by preda** [comment]
OK, the difference in my observations was caused by me running uniformly my 5M exponents with NO_KCOS_ROCM_BUG. This indicates that NO_KCOS_ROCM_BUG has not only correctness implications (good/broken) but also precision impact.

| z(95157709)|default|ULTRA_TRIG|
|---|---|---|
default|20.7|23.8|
NO_KCOS_ROCM_BUG|22|18.1|

Another observation -- on 97000003 with 5M FFT and MM_CHAIN=0,MM2_CHAIN=0 I see almost no difference (with/without ULTRA_TRIG). On 97500061 with 5M FFT and default chain (MM_CHAIN=3,MM2_CHAIN=3) I see very little improvement w. ULTRA_TRIG (13.9 to 14), but big improvement w. NO_KCOS_ROCM_BUG (13.9 to 15).

**Comment by gwoltman** [comment]
I don't know what to make of the precision impact of the rocm bug.   I
thought perhaps rocm was making a legal optimization because of our
-fp-relaxed-math flag.
However I took that out and gpuowl still fails without the NO_KCOS_ROCM_BUG
option.

On another rocm optimizer note.  I'm running a March 23 private version
where I stumbled upon the "holy grail" of tailFusedSquare compilation:

2020-04-06 19:00:20 gfx906+sram-ecc-0 95000003 OK    40000   0.04%;  649
us/it; ETA 0d 17:08; 8ddf9cb5474b2577 (check 0.81s)
2020-04-06 19:00:20 gfx906+sram-ecc-0 39.44% carryFused     :    242
us/call x  5994 calls
2020-04-06 19:00:20 gfx906+sram-ecc-0 26.45% tailFusedSquare :    162
us/call x  6000 calls
2020-04-06 19:00:20 gfx906+sram-ecc-0 17.70% fftMiddleOut   :    108
us/call x  6005 calls
2020-04-06 19:00:20 gfx906+sram-ecc-0 16.21% fftMiddleIn    :     99
us/call x  6010 calls

The current master version is much slower:

2020-04-06 19:04:17 gfx906+sram-ecc-0 95000003 OK   110000   0.12%;  652
us/it; ETA 0d 17:11; a5939e95164cf3f4 (check 0.79s)
2020-04-06 19:04:17 gfx906+sram-ecc-0 38.18% carryFused     :    235
us/call x  9990 calls
2020-04-06 19:04:17 gfx906+sram-ecc-0 28.87% tailFusedSquare :    177
us/call x 10000 calls
2020-04-06 19:04:17 gfx906+sram-ecc-0 16.78% fftMiddleIn    :    103
us/call x 10018 calls
2020-04-06 19:04:17 gfx906+sram-ecc-0 15.95% fftMiddleOut   :     98
us/call x 10009 calls

Do you have any interest in the executable to see if that kernel is also
faster on your machine using rocm 3.3?
We can dump my source and see if we can replicate the fortuitous
tailFusedSquare result.  From past experience
this is a tedious pot-luck process with no guarantee of success.


Regards,
George

**Comment by preda** [comment]
Hi George, sorry for late answer.
The ROCm bug is extremely annoying to the point that I would try to understand a bit better what's happening, it the hope that it may identified and fixed. Otherwise it seems like a slippery surface to work on.

For the sin/cos here, I'd also like to understand the behavior better (to identify the situations where it is not an improvement if any) -- but let me know if you'd prefer to merge it earlier, it being disabled by default.

I would like to check the faster tailFused on 3.3, please send it in what form is convenient -- either a change or diff, or the gpuowl.cl, etc. So do you see an improvement of 5us (overall) with that change?

**Comment by preda** [comment]
George, one more thing, could you please add enough information to allow a third-party to reproduce the derivation of the coefficients. I think adding the auxiliary programs used in deriving these would be great -- probably in a separate folder, or under tools/ etc.

**Comment by preda** [comment]
Merged, without the FFT bounds update.

In ROCm 3.3, FFT 5M, using ULTRA_TRIG loses 5us.

**Pull request closed without merging**
