### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by valeriob01**
Add -maxAlloc

### CODE REVIEW

**Comment by preda** [comment]
Thanks, this is now done, sorry I didn't merge it earlier.

**Comment by valeriob01** [comment]
But I don't see the change, and I have another one to add.

**Comment by preda** [comment]
https://github.com/preda/gpuowl/blob/master/Args.cpp
-maxAlloc is there, isn't it?
you may click on "Blame" (top-right) and see how it got there.

**Comment by preda** [comment]
OK my bad, I was looking at help not at README

**Comment by selroc** [comment]
> OK my bad, I was looking at help not at README

:-) okay, now there is -yield to add I think.

**Pull request merged**
